### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by qwertybba** [DevExpress-Examples/blazor-DxDataGrid-Separate-Edit-Form#5]
Hello;
I get this error when I try to build the application for the first time

> error RZ10001: The type of component 'DxComboBox' cannot be inferred based on the values provided. Consider specifying the type arguments directly using the following attributes: 'TData', 'TValue'

and when I open SeparateEditForm.razor I get several errors:
The first one 
> Error	CS1660	Cannot convert lambda expression to type 'EventCallback' because it is not a delegate type
`
ItemUpdating=@((fieldName, newValue) => OnItemUpdating(fieldName, newValue))`

The second and the third
> Error	RZ10001	The type of component 'DxComboBox' cannot be inferred based on the values provided. Consider specifying the type arguments directly using the following attributes: 'TData', 'TValue'.

> Error	CS0246	The type or namespace name 'ValueEditingContext' could not be found (are you missing a using directive or an assembly reference?)
`<DxComboBox Data=@summaries
                            SelectedItem=@(((string)((ValueEditingContext)context).Value))
                            SelectedItemChanged=@(value => ((ValueEditingContext)context).OnChanged(value))></DxComboBox>`

and the last one is
> Error	CS1662	Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type

**Comment by CodeKarno** [comment]
Hi,

From what I gather, you are using a newer version of DevExpress Blazor components. It has some changes in the API. I added a branch with a new DevExpress version (v20.2.3+) to this example: [https://github.com/DevExpress-Examples/blazor-DxDataGrid-Separate-Edit-Form/pull/6](https://github.com/DevExpress-Examples/blazor-DxDataGrid-Separate-Edit-Form/pull/6)
Please check its implementation.
If you have further questions regarding DevExpress components, feel free to submit a ticket to our Support Center: [DevExpress - Submit a Ticket](https://devexpress.com/ask).
